modules_dir = "."
total_memory_limit = "Infinity"

[[module]]
name = "sqlite3"
mem_pages_count = 100
logger_enabled = false

[module.wasi]
preopened_files = []
mapped_dirs = { "tmp" = ".", "storage" = "." }

[[module]]
name = "spell"
