modules_dir = "."
total_memory_limit = "Infinity"

[[module]]
name = "sqlite3"
mem_pages_count = 100
logger_enabled = false
[module.wasi]
mapped_dirs = { "/storage" = "./tests_artifacts" }

[[module]]
name = "spell"
[module.wasi]
mapped_dirs = { "/storage" = "./tests_artifacts" }
