networks:
  nox:
    driver: bridge
    ipam:
      config:
      - subnet: 10.50.10.0/24

services:
  nox-1:
    image: ${NOX_IMAGE}
    ports:
      - 7771:7771
      - 9991:9991
    command:
      - --aqua-pool-size=2
      - -t=7771
      - -w=9991
      - -x=10.50.10.10
      - --external-maddrs
      - /dns4/nox-1/tcp/7771
      - /dns4/nox-1/tcp/9991/ws
      - --allow-private-ips
      - --local
      # - --bootstraps=/dns/nox-1/tcp/7771
      # 12D3KooWBM3SdXWqGaawQDGQ6JprtwswEg3FWGvGhmgmMez1vRbR
      - -k=hK62afickoeP2uZbmSkAYXxxqP8ozq16VRN7qfTP719EHC5V5tjrtW57BSjUr8GvsEXmJRbtejUWyPZ2rZMyQdq
      - --enable-system-services=none
      - --management-key=12D3KooWGLAmtTkqZqqKiSxXpb2j1SRjpbE2YgZZb4Unzn5VPj9p
      - --dev-mode
    networks:
      nox:
        ipv4_address: 10.50.10.10
