[package]
name = "spell"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "spell"
path = "src/main.rs"

[dependencies]
marine-rs-sdk = "0.7.1"
marine-sqlite-connector = "0.6.0"
anyhow = "1.0.65"
cid = "0.8.6"
thiserror = "1.0.37"

[dev-dependencies]
marine-rs-sdk-test = "0.8.1"
