[workspace]
resolver = "2"
members = [
  "spell",
  "spell-dtos",
  "spell-distro"
]

[workspace.dependencies]
marine-sqlite-connector = "0.11.0"
marine-rs-sdk = "0.12.0"
fluence-app-serivce = "0.32.0"
