[workspace]
resolver = "2"
members = [
  "spell",
  "spell-dtos",
  "spell-distro"
]

[workspace.dependencies]
marine-sqlite-connector = "0.9.3"
#marine-sqlite-connector =  { path = "/home/maar/Fluence/sqlite-wasm-connector" }
