name: "ci"

on:
  pull_request:
    paths-ignore:
      - "**.md"

  push:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  spell:
    uses: ./.github/workflows/tests.yml
    with:
      ref: ${{ github.ref }}

  cargo:
    name: "spell / Run cargo tests"
    runs-on: builder
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v3

      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Setup marine
        uses: fluencelabs/setup-marine@v1

      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1.3.0
        with:
          crate: cargo-nextest

      - name: Test spell
        working-directory: ./src/spell/modules/spell/spell
        run: ./test.sh
