name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/snapshot.yml"
    types:
      - "labeled"
      - "synchronize"
      - "opened"
      - "reopened"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/snapshot.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  snapshot:
    if: >
      github.event_name == 'push' ||
      contains(github.event.pull_request.labels.*.name, 'e2e')
    name: "spell"
    uses: ./.github/workflows/snapshot.yml
    with:
      ref: ${{ github.ref }}

  installation-spell:
    name: "spell / Check installation spell compiles"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: fluencelabs/spell
          ref: ${{ github.ref }}

      - name: Setup node with self-hosted registry
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://npm.fluence.dev"

      - run: npm install
        working-directory: src/aqua/installation-spell

      - run: npm run check
        working-directory: src/aqua/installation-spell

  decider:
    needs:
      - snapshot
    uses: fluencelabs/decider/.github/workflows/snapshot.yml@main
    with:
      cargo-dependencies: |
        [
          {
            "package": "fluence-spell-dtos",
            "version": "=${{ needs.snapshot.outputs.cargo-version }}",
            "manifest": "src/distro/Cargo.toml",
            "registry": "fluence"
          }
        ]

  nox:
    needs:
      - decider
      - snapshot
    uses: fluencelabs/nox/.github/workflows/build.yml@master
    with:
      cargo-dependencies: |
        [
          {
            "package": "fluence-spell-dtos",
            "version": "=${{ needs.snapshot.outputs.cargo-version }}",
            "registry": "fluence"
          },
          {
            "package": "fluence-spell-distro",
            "version": "=${{ needs.snapshot.outputs.cargo-version }}",
            "registry": "fluence"
          },
          {
            "package": "decider-distro",
            "version": "=${{ needs.decider.outputs.cargo-version }}",
            "manifest": "crates/system-services/Cargo.toml",
            "registry": "fluence"
          }
        ]

  nox-snapshot:
    name: "nox"
    needs:
      - nox

    uses: fluencelabs/nox/.github/workflows/container.yml@master
    with:
      image-name: "docker.fluence.dev/spell"
      flavour: "minimal"
      nox-sha: "${{ needs.nox.outputs.nox-sha }}"

  nox-tests:
    name: "nox"
    needs:
      - snapshot
      - decider

    uses: fluencelabs/nox/.github/workflows/tests.yml@master
    with:
      cargo-dependencies: |
        [
          {
            "package": "fluence-spell-dtos",
            "version": "=${{ needs.snapshot.outputs.cargo-version }}",
            "registry": "fluence"
          },
          {
            "package": "fluence-spell-distro",
            "version": "=${{ needs.snapshot.outputs.cargo-version }}",
            "registry": "fluence"
          },
          {
            "package": "decider-distro",
            "version": "=${{ needs.decider.outputs.cargo-version }}",
            "manifest": "crates/system-services/Cargo.toml",
            "registry": "fluence"
          }
        ]

  aqua-tests:
    name: "spell"
    needs:
      - nox-snapshot
    uses: ./.github/workflows/tests.yml
    with:
      ref: ${{ github.ref }}
      nox-image: "${{ needs.nox-snapshot.outputs.nox-image }}"
