name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/snapshot.yml"
    types:
      - "labeled"
      - "synchronize"
      - "opened"
      - "reopened"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/snapshot.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  snapshot:
    if: >
      github.event_name == 'push' ||
      contains(github.event.pull_request.labels.*.name, 'e2e')
    name: "spell"
    uses: ./.github/workflows/snapshot.yml
    with:
      ref: ${{ github.ref }}

  rust-peer:
    needs:
      - snapshot

    uses: fluencelabs/rust-peer/.github/workflows/build.yml@master
    with:
      cargo-dependencies: |
        [
          {
            "package": "fluence-spell-dtos",
            "version": "=${{ needs.snapshot.outputs.cargo-version }}",
            "registry": "fluence"
          },
          {
            "package": "fluence-spell-distro",
            "version": "=${{ needs.snapshot.outputs.cargo-version }}",
            "registry": "fluence"
          }
        ]

  rust-peer-snapshot:
    name: "rust-peer"
    needs:
      - rust-peer

    uses: fluencelabs/rust-peer/.github/workflows/container.yml@master
    with:
      image-name: "docker.fluence.dev/spell"
      flavour: "minimal"
      rust-peer-sha: "${{ needs.rust-peer.outputs.rust-peer-sha }}"

  rust-peer-tests:
    name: "rust-peer"
    needs:
      - snapshot

    uses: fluencelabs/rust-peer/.github/workflows/tests.yml@master
    with:
      cargo-dependencies: |
        [
          {
            "package": "fluence-spell-dtos",
            "version": "=${{ needs.snapshot.outputs.cargo-version }}",
            "registry": "fluence"
          },
          {
            "package": "fluence-spell-distro",
            "version": "=${{ needs.snapshot.outputs.cargo-version }}",
            "registry": "fluence"
          }
        ]

  aqua-tests:
    name: "spell"
    needs:
      - rust-peer-snapshot
    uses: ./.github/workflows/tests.yml
    with:
      ref: ${{ github.ref }}
      rust-peer-image: "${{ needs.rust-peer-snapshot.outputs.rust-peer-image }}"
