name: "e2e"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/snapshot.yml"
    types:
      - "labeled"
      - "synchronize"
      - "opened"
      - "reopened"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/e2e.yml"
      - "!.github/workflows/snapshot.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  snapshot:
    if: >
      github.event_name == 'push' ||
      contains(github.event.pull_request.labels.*.name, 'e2e')
    name: "spell"
    uses: ./.github/workflows/snapshot.yml
    with:
      ref: ${{ github.ref }}

  decider:
    needs:
      - snapshot
    uses: fluencelabs/decider/.github/workflows/snapshot.yml@main
    with:
      cargo-dependencies: |
        [
          {
            "package": "fluence-spell-dtos",
            "version": "=${{ needs.snapshot.outputs.cargo-version }}",
            "registry": "fluence"
          }
        ]

  nox:
    needs:
      - decider
      - snapshot
    uses: fluencelabs/nox/.github/workflows/build.yml@master
    with:
      cargo-dependencies: |
        [
          {
            "package": "fluence-spell-dtos",
            "version": "=${{ needs.snapshot.outputs.cargo-version }}",
            "registry": "fluence"
          },
          {
            "package": "fluence-spell-distro",
            "version": "=${{ needs.snapshot.outputs.cargo-version }}",
            "registry": "fluence"
          },
          {
            "package": "decider-distro",
            "version": "=${{ needs.decider.outputs.cargo-version }}",
            "manifest": "crates/system-services/Cargo.toml",
            "registry": "fluence"
          }
        ]

  nox-snapshot:
    name: "nox"
    needs:
      - nox

    uses: fluencelabs/nox/.github/workflows/container.yml@master
    with:
      image-name: "docker.fluence.dev/spell"
      flavour: "minimal"
      nox-sha: "${{ needs.nox.outputs.nox-sha }}"

  nox-tests:
    name: "nox"
    needs:
      - snapshot
      - decider

    uses: fluencelabs/nox/.github/workflows/tests.yml@master
    with:
      cargo-dependencies: |
        [
          {
            "package": "fluence-spell-dtos",
            "version": "=${{ needs.snapshot.outputs.cargo-version }}",
            "registry": "fluence"
          },
          {
            "package": "fluence-spell-distro",
            "version": "=${{ needs.snapshot.outputs.cargo-version }}",
            "registry": "fluence"
          },
          {
            "package": "decider-distro",
            "version": "=${{ needs.decider.outputs.cargo-version }}",
            "manifest": "crates/system-services/Cargo.toml",
            "registry": "fluence"
          }
        ]

  aqua-tests:
    name: "spell"
    needs:
      - nox-snapshot
    uses: ./.github/workflows/tests.yml
    with:
      ref: ${{ github.ref }}
      nox-image: "${{ needs.nox-snapshot.outputs.nox-image }}"

  cli:
    needs:
      - snapshot
      - nox-snapshot

    uses: fluencelabs/cli/.github/workflows/tests.yml@main
    with:
      nox-image: "${{ needs.nox-snapshot.outputs.nox-image }}"
      spell-version: "${{ needs.snapshot.outputs.spell-version }}"
      installation-spell-version: "${{ needs.snapshot.outputs.installation-spell-version }}"

  cli-snapshot:
    name: "cli"
    needs:
      - snapshot

    uses: fluencelabs/cli/.github/workflows/snapshot.yml@main
    with:
      spell-version: "${{ needs.snapshot.outputs.spell-version }}"
      installation-spell-version: "${{ needs.snapshot.outputs.installation-spell-version }}"
