name: "release"

on:
  push:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  release-please:
    runs-on: ubuntu-latest

    outputs:
      releases-created: ${{ steps.release.outputs.releases_created }}

      spell-release-created: ${{ steps.release.outputs['spell--release_created'] }}
      spell-tag-name: ${{ steps.release.outputs['spell--tag_name'] }}

      spell-distro-release-created: ${{ steps.release.outputs['spell-distro--release_created'] }}
      spell-distro-tag-name: ${{ steps.release.outputs['spell-distro--tag_name'] }}

      spell-dtos-release-created: ${{ steps.release.outputs['spell-dtos--release_created'] }}
      spell-dtos-tag-name: ${{ steps.release.outputs['spell-dtos--tag_name'] }}

    steps:
      - name: Run release-please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/manifest.json

      - name: Show output from release-please
        if: steps.release.outputs.releases_created
        env:
          RELEASE_PLEASE_OUTPUT: ${{ toJSON(steps.release.outputs) }}
        run: echo "${RELEASE_PLEASE_OUTPUT}" | jq


  spell:
    runs-on: ubuntu-latest

    needs: release-please
    if: ${{ needs.release-please.outputs.releases-created }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install Marine
        uses: baptiste0928/cargo-install@v1.3.0
        with:
          crate: marine

      - name: Build and package spell
        working-directory: ./src/spell/modules/spell/spell
        run: ./build.sh
