name: "test"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/tests.yml"
      - "!.github/workflows/run-tests.yml"
  push:
    branches:
      - "main"
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/tests.yml"
      - "!.github/workflows/run-tests.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  installation-spell:
    name: "Check installation spell compiles"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: fluencelabs/spell
          ref: ${{ github.ref }}

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8

      - name: Setup node with self-hosted npm registry
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://npm.fluence.dev"
          cache: "pnpm"

      - run: pnpm install
        working-directory: src/aqua/installation-spell

      - run: pnpm run check
        working-directory: src/aqua/installation-spell
