name: "test"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/tests.yml"
      - "!.github/workflows/run-tests.yml"
  push:
    branches:
      - "master"
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "!.github/workflows/tests.yml"
      - "!.github/workflows/run-tests.yml"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  spell:
    uses: ./.github/workflows/snapshot.yml
    with:
      ref: ${{ github.ref }}
      snapshot: false

  spell-aqua:
    name: spell
    uses: ./.github/workflows/tests.yml
    with:
      ref: ${{ github.ref }}

  installation-spell:
    name: "spell / Check installation spell compiles"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: fluencelabs/spell
          ref: ${{ github.ref }}

      - name: Setup node with self-hosted registry
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          registry-url: "https://npm.fluence.dev"

      - run: npm install
        working-directory: src/aqua/installation-spell

      - run: npm run check
        working-directory: src/aqua/installation-spell
