name: Build snapshot

on:
  workflow_call:
    inputs:
      cargo-dependencies:
        description: "Cargo dependencies map"
        type: string
        default: "null"
      ref:
        description: "git ref to checkout to"
        type: string
        default: "main"
      snapshot:
        description: "Whether to publish snapshots"
        type: boolean
        default: true
    outputs:
      cargo-version:
        description: "Cargo snapshot version"
        value: ${{ jobs.snapshot.outputs.version }}

env:
  CARGO_UNSTABLE_SPARSE_REGISTRY: true

jobs:
  snapshot:
    name: "Build and test crates"
    runs-on: builder
    timeout-minutes: 60

    outputs:
      version: "${{ steps.snapshot.outputs.version }}"

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          repository: fluencelabs/spell
          ref: ${{ inputs.ref }}

      - name: Setup Rust toolchain
        uses: dsherret/rust-toolchain-file@v1

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: spell
          # github allows only 10GB of cache
          # so save cache only on merge to master
          # to use less space and speed up CI
          save-if: ${{ github.event_name == 'push' }}

      - name: Setup cargo-nextest
        uses: taiki-e/install-action@nextest

      - name: Set dependencies
        if: inputs.cargo-dependencies != 'null'
        uses: fluencelabs/github-actions/cargo-set-dependency@main
        with:
          dependencies: ${{ inputs.cargo-dependencies }}
          path: src/spell/modules/spell

      - name: Setup marine
        uses: fluencelabs/setup-marine@v1
        with:
          artifact-name: marine

      - name: Build and package spell
        working-directory: ./src/spell/modules/spell/spell
        run: ./build.sh

      - name: Run tests
        working-directory: ./src/spell/modules/spell/spell
        run: ./test.sh

      - name: Import secrets
        if: inputs.snapshot == true
        uses: hashicorp/vault-action@v2.5.0
        with:
          url: https://vault.fluence.dev
          path: jwt/github
          role: ci
          method: jwt
          jwtGithubAudience: "https://github.com/fluencelabs"
          jwtTtl: 300
          exportToken: false
          secrets: |
            kv/cargo-registry/users/ci token | CARGO_REGISTRIES_FLUENCE_TOKEN

      - name: Generate snapshot version
        if: inputs.snapshot == true
        id: version
        uses: fluencelabs/github-actions/generate-snapshot-id@main

      - name: Publish crate snapshots
        if: inputs.snapshot == true
        id: snapshot
        uses: fluencelabs/github-actions/cargo-publish-snapshot@main
        with:
          id: ${{ steps.version.outputs.id }}
          path: src/spell/modules/spell
